Kitchen/Models/IngridientViewModel.cs
namespace Kitchen.Models
{
    public class IngridientViewModel
    {
        public string Ammount;
        public string MeasureName;
        public string Name;
    }
}

Kitchen/Models/SimpleRecipeViewModel.cs
namespace Kitchen.Models
{
    public class SimpleRecipeViewModel
    {
        public string Name;
        public string Description;
        public IngridientViewModel[] Ingridients;
    }

}

Kitchen/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Database;
using Database.Accessors;

namespace Kitchen.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            var reader = RecipeAccessor.Instance;
            var lastAdded = reader.LastUpdated(20);
            ViewBag.Entries = lastAdded;
            return View();
        }

    }
}

Kitchen/Controllers/RecipesController.cs
using System.Web.Mvc;
using Database.Ingredients;
using Database.Models;
using Kitchen.Models;
using Database.Accessors;

namespace Kitchen.Controllers
{
    public class RecipesController : Controller
    {
        //
        // GET: /Recipes/

        public ActionResult Index(int id=0)
        {
            if (id==0)
            {
                id = 2;//S.Rozhin todo for normal
            }
            var reader = RecipeAccessor.Instance;
            var readed = GetFakeRecipeForDebug();//reader.SelectById(id);
            return View(readed);
        }

        private SimpleRecipeViewModel GetFakeRecipeForDebug()
        {
            return new SimpleRecipeViewModel
                {
                    Name = "Сэндвич с сливочным сыром и лососем",
                    Description =
                        "Кофе в кемексе получается нежным и лишённым горечи, мягким и с яркой индивидуальностью.",
                    Ingridients = new[]
                        {
                                    new IngridientViewModel
                                        {
                                            Ammount = "2",
                                            MeasureName = MeasureType.TeaSpoon.ToString(),
                                                    //Description = "обычный тип продукта",
                                            Name = "Солъ"
                                        },
                                     new IngridientViewModel
                                        {
                                            Ammount = "1",
                                            MeasureName = MeasureType.AtTaste.ToString(),
                                                    //Description = "не обычный тип продукта",
                                            Name = "Перец"
                                        }
                                   
                                }
                };
        }

        //
        // GET: /Recipes/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Recipes/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Recipes/Create

        [HttpPost]
        public ActionResult Create(FormCollection data)
        {
            try
            {
                var toSubmit = new BaseRecipe {Name = data["Name"], Description = data["Description"]};
                var ingrName = data["IngridientName"];
                var ingrAmm = data["IngridientAmmount"];
                RecipeAccessor.Instance.Insert(toSubmit);
                return Content("Рецепт успешно сохранён в книге");//RedirectToAction("Index");
            }
            catch
            {
                return Content("Не удалось сохранить рецепт");
            }
        }

        //
        // GET: /Recipes/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Recipes/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Recipes/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Recipes/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Kitchen/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Книга рецептов";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align: center;">Поиск по рецептам</h2>
<div class="span3" style="width: 23%">
    <div class="well sidebar-nav">
        <ul class="nav nav-list">
            <li class="nav-header">Рецепты дня</li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li class="nav-header">Другие Рецепты дня</li>
             <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
        </ul>
    </div>
</div>
<div style="text-align: left; float: left">
    <a href="@Url.Action("Index", "Recipes")">Рецепт дня</a>
    @*@Html.ActionLink("Пользователи",  "Index", "Recipes")*@
</div>

Kitchen/Views/Recipes/Create.cshtml
@using Kitchen.Auxillary
@{
    ViewBag.Title = "Добавление рецепта в книгу";
}

<div class="row">
    <div class="span2"></div>
    <div class="span9">
        <h2>Опиши свой новый рецепт:</h2>
        <form method="post" action="">
            <fieldset>
                <div class="control-group">
                    <label for="inptRecipeName" class="control-label">Как называется этот рецепт?</label>
                    <div class="controls">
                        <input type="text" name="Name" id="inptRecipeName" maxlength="200" />
                    </div>
                </div>
                Какие в нём есть ингридиенты?
                <table data-bind='visible: ingredients().length > 0' class="table">
                    <thead>
                        <tr>
                            <th>Название продукта</th>
                            <th>Количество</th>
                            <th />
                            <th />
                        </tr>
                    </thead>
                    <tbody data-bind='foreach: ingredients'>
                        <tr>
                            <td style="border-top: transparent">
                                <input type="text" name="IngridientName" maxlength="200" data-bind='value: name, uniqueName: true' /></td>
                            <td style="border-top: transparent">
                                <input type="number" data-bind='value: ammount, uniqueName: true' /></td>
                            <td style="border-top: transparent">
                                @Html.DropDownList("MeasureType", MeasureHelperTemp.ProductMeasureSelectList,new Dictionary<string, object> {{"data-bind","value: measure, uniqueName: true"}})
                            </td>
                            <td  style="border-top: transparent"><a href='#' data-bind='click: $root.removeIngredient'>Удалить</a></td>
                        </tr>
                    </tbody>
                </table>
                <button data-bind='click: addIngredient'>Добавить продукт</button>
                <button data-bind='click: save'>Show me Json</button>
                <button data-bind='enable: ingredients().length > 0' type='submit'>Submit</button>
                <div class="control-group">
                    <label for="txtDescription" class="control-label">Как его приготовить?</label>
                    <div class="controls">
                        <textarea name="Description" rows="10" cols="40" id="txtDescription"></textarea>
                    </div>
                    <br />

                    <br />
                </div>
                <input type="submit" value="Сохранить рецепт" />

            </fieldset>
        </form>
    </div>
    <div class="span1"></div>
</div>
<script type="text/javascript" language="javascript">
    var IngredientModel = function (ingredients) {
        var self = this;
        self.ingredients = ko.observableArray(ingredients);

        self.addIngredient = function () {
            self.ingredients.push({
                name: "",
                ammount: 0,
                measure: 1
            });
        };

        self.removeIngredient = function (ingredient) {
            self.ingredients.remove(ingredient);
        };

        self.save = function (form) {
            alert("Could now transmit to server: " + ko.utils.stringifyJson(self.ingredients));
            // To actually transmit to server as a regular form post, write this: ko.utils.postJson($("form")[0], self.gifts);
        };
    };

    var viewModel = new IngredientModel([
        { name: "Соль", ammount: 0, measure: 1 },
        { name: "Хлеб", ammount: 10, measure: 0 }
    ]);
    ko.applyBindings(viewModel);

    // Activate jQuery Validation
    //$("form").validate({ submitHandler: viewModel.save });
    </script>

Kitchen/Views/Recipes/Index.cshtml
@model Kitchen.Models.SimpleRecipeViewModel

@{
    ViewBag.Title = "Рецепты: " + Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="span4"></div>
    <div class="span7">
        <h2>@Model.Name</h2>
        <div>
            @Model.Description
        </div>
        <div>
            <table class="table table-striped table-hover">
                <tr>
                    <th>Название</th>
                    <th>Количество</th>
                    <th>Единицы измерения</th>
                </tr>
                @foreach (var ingridient in Model.Ingridients)
                {
                    <tr>
                        <td>@ingridient.Name</td>
                        <td>@ingridient.Ammount </td>
                        <td>@ingridient.MeasureName</td>
                    </tr>
                }
            </table>
        </div>
    </div>
    <div class="span1"></div>
</div>

Kitchen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @RenderSection("styles", required:false)
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/knockout")
</head>
    <body>

        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="@Url.Action("Index","Recipes")">Кухня</a>
                    <div class="nav-collapse collapse">
                        <p class="navbar-text pull-right">
                            Вы вошли как <a href="#" class="navbar-link">тут будет юзернэйм</a>
                        </p>
                        <ul class="nav">
                            <li class="dropdown active">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Рецепты <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Поиск</a></li>
                                    <li><a href="@Url.Action("Create", "Recipes")">Добавить свой</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li class="nav-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
                            <li><a href="#about">О проекте</a></li>
                            <li><a href="#contact">Напишите нам</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        @RenderBody()

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>